[workspace]
members = [".", "bin"]

[workspace.dependencies]
thiserror = "2.0.12"

[package]
name = "preclang"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
thiserror = { workspace = true }
